<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.pagination' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataProvider/Pagination.php';

return $this->privates['api_platform.pagination'] = new \ApiPlatform\Core\DataProvider\Pagination(($this->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), $this->parameters['api_platform.collection.pagination']);
