<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.api_platform.data_persister.inner' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataPersister/ContextAwareDataPersisterInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataPersister/ChainDataPersister.php';

return $this->privates['debug.api_platform.data_persister.inner'] = new \ApiPlatform\Core\DataPersister\ChainDataPersister(new RewindableGenerator(function () {
    yield 0 => ($this->privates['api_platform.doctrine.orm.data_persister'] ?? $this->load('getApiPlatform_Doctrine_Orm_DataPersisterService.php'));
}, 1));
