<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.V0Dhlp5' shared service.

return $this->privates['.service_locator.V0Dhlp5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ListeController::index' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\NeldamController::ajout' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\NeldamController::compte' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\NeldamController::depot' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\NeldamController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UpdateController::index' => ['privates', '.service_locator.BSb3rX6', 'get_ServiceLocator_BSb3rX6Service.php', true],
    'App\\Controller\\ListeController:index' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\NeldamController:ajout' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\NeldamController:compte' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\NeldamController:depot' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\NeldamController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UpdateController:index' => ['privates', '.service_locator.BSb3rX6', 'get_ServiceLocator_BSb3rX6Service.php', true],
], [
    'App\\Controller\\ListeController::index' => '?',
    'App\\Controller\\NeldamController::ajout' => '?',
    'App\\Controller\\NeldamController::compte' => '?',
    'App\\Controller\\NeldamController::depot' => '?',
    'App\\Controller\\NeldamController::register' => '?',
    'App\\Controller\\UpdateController::index' => '?',
    'App\\Controller\\ListeController:index' => '?',
    'App\\Controller\\NeldamController:ajout' => '?',
    'App\\Controller\\NeldamController:compte' => '?',
    'App\\Controller\\NeldamController:depot' => '?',
    'App\\Controller\\NeldamController:register' => '?',
    'App\\Controller\\UpdateController:index' => '?',
]);
