<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.routing.loader.reader.action' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Routing/Loader/Reader/RestActionReader.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Inflector/InflectorInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Inflector/DoctrineInflector.php';

return $this->privates['fos_rest.routing.loader.reader.action'] = new \FOS\RestBundle\Routing\Loader\Reader\RestActionReader(($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()), ($this->privates['fos_rest.request.param_fetcher.reader'] ?? $this->load('getFosRest_Request_ParamFetcher_ReaderService.php')), ($this->privates['fos_rest.inflector.doctrine'] ?? ($this->privates['fos_rest.inflector.doctrine'] = new \FOS\RestBundle\Inflector\DoctrineInflector())), true, ['json' => false, 'xml' => false, 'html' => true], true);
