<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_jwt_authentication.extractor.chain_extractor' shared service.

include_once $this->targetDirs[3].'/vendor/lexik/jwt-authentication-bundle/TokenExtractor/TokenExtractorInterface.php';
include_once $this->targetDirs[3].'/vendor/lexik/jwt-authentication-bundle/TokenExtractor/ChainTokenExtractor.php';
include_once $this->targetDirs[3].'/vendor/lexik/jwt-authentication-bundle/TokenExtractor/AuthorizationHeaderTokenExtractor.php';

return $this->privates['lexik_jwt_authentication.extractor.chain_extractor'] = new \Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\ChainTokenExtractor([0 => ($this->privates['lexik_jwt_authentication.extractor.authorization_header_extractor'] ?? ($this->privates['lexik_jwt_authentication.extractor.authorization_header_extractor'] = new \Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\AuthorizationHeaderTokenExtractor('Bearer', 'Authorization')))]);
