<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.context.api' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-bundle/Security/FirewallContext.php';

return $this->privates['security.firewall.map.context.api'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () {
    yield 0 => ($this->privates['security.channel_listener'] ?? $this->load('getSecurity_ChannelListenerService.php'));
    yield 1 => ($this->privates['security.authentication.listener.guard.api'] ?? $this->load('getSecurity_Authentication_Listener_Guard_ApiService.php'));
    yield 2 => ($this->privates['security.authentication.listener.json.api'] ?? $this->load('getSecurity_Authentication_Listener_Json_ApiService.php'));
    yield 3 => ($this->privates['security.authentication.listener.basic.api'] ?? $this->load('getSecurity_Authentication_Listener_Basic_ApiService.php'));
    yield 4 => ($this->privates['security.authentication.listener.anonymous.api'] ?? $this->load('getSecurity_Authentication_Listener_Anonymous_ApiService.php'));
    yield 5 => ($this->privates['security.access_listener'] ?? $this->load('getSecurity_AccessListenerService.php'));
}, 6), ($this->privates['security.exception_listener.api'] ?? $this->load('getSecurity_ExceptionListener_ApiService.php')), NULL, ($this->privates['security.firewall.map.config.api'] ?? $this->load('getSecurity_Firewall_Map_Config_ApiService.php')));
