<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BSb3rX6' shared service.

return $this->privates['.service_locator.BSb3rX6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'part' => ['privates', '.errored..service_locator.BSb3rX6.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.BSb3rX6": it references class "App\\Entity\\Partenaire" but no such service exists.'],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'entityManager' => '?',
    'part' => 'App\\Entity\\Partenaire',
    'serializer' => '?',
    'validator' => '?',
]);
