<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqqPsiq\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqqPsiq/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSqqPsiq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSqqPsiq\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerSqqPsiq\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'SqqPsiq',
    'container.build_id' => '57d9f801',
    'container.build_time' => 1564564170,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqqPsiq');
