<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF4zZpGR\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF4zZpGR/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerF4zZpGR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerF4zZpGR\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerF4zZpGR\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'F4zZpGR',
    'container.build_id' => 'eb311eaa',
    'container.build_time' => 1564403568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF4zZpGR');
