<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcesUMZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcesUMZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJcesUMZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJcesUMZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJcesUMZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JcesUMZ',
    'container.build_id' => 'a18a8f1e',
    'container.build_time' => 1564477483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcesUMZ');
