<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL4zhweI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL4zhweI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL4zhweI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL4zhweI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerL4zhweI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'L4zhweI',
    'container.build_id' => 'af01491e',
    'container.build_time' => 1564563934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL4zhweI');
